import xml.etree.ElementTree as ET

translations = {
    'ko': {
        'WebP Conversion Options': 'WebP 변환 옵션',
        'Conversion Options': '변환 옵션',
        'Lossless': '무손실 압축',
        'Image Quality': '이미지 품질',
        'Exif Data': 'EXIF 데이터 유지',
        'ICC Profile': 'ICC 프로파일 유지',
        'Transparent RGB': '투명 배경 유지(RGB)',
        'Exif Frame Options': 'EXIF 프레임 옵션',
        'Caption Options': '프레임 텍스트 옵션',
        'Select Font': '폰트 선택',
        'Alignment': '텍스트 위치',
        'Center': '중앙',
        'Left': '왼쪽',
        'Right': '오른쪽',
        'EXIF Easy Mode': '간편 설정',
        'One line': '한 줄 쓰기',
        'Text Color': '텍스트 색상',
        'BG Color': '배경 색상',
        'Loading...': '로딩 중...',
        'Automatically hide NONEDATA text': '데이터 없는 항목 숨기기',
        'EXIF Options': 'EXIF 옵션',
        'Padding Option': '프레임 구성 옵션',
        'No Padding': '프레임 없음',
        'Bottom': '하단 프레임',
        'Frame': '전체 프레임',
        'Save Exif Data': 'EXIF 데이터 저장',
        'Ratio': '비율',
        'Original': '원본 비율',
        'Square': '1:1 (정방형)',
        '4:5': '4:5 비율',
        'Quality': '품질',
        'Image Type': '이미지 타입',
        'JPEG': 'JPEG',
        'PNG': 'PNG',
        'WebP': 'WebP',
        'Settings': '환경설정',
        'Language': '언어',
        'English': 'English (영어)',
        'Korean': '한국어',
        'Japanese': '日本語 (일본어)',
        'Add Text': '텍스트 추가',
        'Watermark Options': '워터마크 옵션',
        'Watermark Text': '워터마크 텍스트',
        'Paddie。': 'Paddie。',
        '+': '+',
        'Enable': '활성화',
        'Options': '설정',
        'TBD': '준비 중',
        'Show Preview': '미리보기',
        "Save to selected photo's path": '선택한 사진과 같은 위치에 저장',
        '-': '-',
        'Resize Options': '크기 조정 옵션',
        'Files': '파일',
        'Add Files': '파일 추가',
        'Ctrl+O': 'Ctrl+O',
        'Remove Files ...': '파일 제거 ...',
        'Exit': '종료',
        'Clear List': '목록 지우기',
        'Preferences': '환경설정...',
        'Information': '정보',
        'Version: ': '버전: ',
        'Contact: ': '문의: ',
        'License: ': '라이선스: ',
        'Axis': '기준 축',
        'Width': '가로 (너비)',
        'Height': '세로 (높이)',
        'Longest': '긴 축',
        'Shortest': '짧은 축',
        'Size': '크기'
    },
    'ja': {
        'WebP Conversion Options': 'WebP 変換オプション',
        'Conversion Options': '変換オプション',
        'Lossless': 'ロスレス圧縮',
        'Image Quality': '画質',
        'Exif Data': 'EXIFデータ保持',
        'ICC Profile': 'ICCプロファイル保持',
        'Transparent RGB': '透明背景保持(RGB)',
        'Exif Frame Options': 'EXIFフレームオプション',
        'Caption Options': 'フレームテキストオプション',
        'Select Font': 'フォント選択',
        'Alignment': 'テキスト位置',
        'Center': '中央',
        'Left': '左',
        'Right': '右',
        'EXIF Easy Mode': '簡単設定',
        'One line': '1行で表示',
        'Text Color': 'テキスト色',
        'BG Color': '背景色',
        'Loading...': 'ロード中...',
        'Automatically hide NONEDATA text': '空のデータを非表示',
        'EXIF Options': 'EXIF オプション',
        'Padding Option': 'パディング設定',
        'No Padding': 'パディングなし',
        'Bottom': '下部パディング',
        'Frame': '全体パディング',
        'Save Exif Data': 'EXIF情報保存',
        'Ratio': '比率',
        'Original': 'オリジナル',
        'Square': '1:1 (正方形)',
        '4:5': '4:5',
        'Quality': '画質',
        'Image Type': '画像形式',
        'JPEG': 'JPEG',
        'PNG': 'PNG',
        'WebP': 'WebP',
        'Settings': '設定',
        'Language': '言語',
        'English': 'English',
        'Korean': '韓国語',
        'Japanese': '日本語',
        'Add Text': 'テキスト追加',
        'Watermark Options': '透かしオプション',
        'Watermark Text': '透かしテキスト',
        'Paddie。': 'Paddie。',
        '+': '+',
        'Enable': '有効にする',
        'Options': 'オプション',
        'TBD': '準備中',
        'Show Preview': 'プレビュー',
        "Save to selected photo's path": '元の写真と同じ場所に保存',
        '-': '-',
        'Resize Options': 'リサイズオプション',
        'Files': 'ファイル',
        'Add Files': 'ファイル追加',
        'Ctrl+O': 'Ctrl+O',
        'Remove Files ...': 'ファイル削除 ...',
        'Exit': '終了',
        'Clear List': 'リストクリア',
        'Preferences': '環境設定...',
        'Information': '情報',
        'Version: ': 'バージョン: ',
        'Contact: ': '連絡先: ',
        'License: ': 'ライセンス: ',
        'Axis': '基準軸',
        'Width': '幅',
        'Height': '高さ',
        'Longest': '長辺',
        'Shortest': '短辺',
        'Size': 'サイズ'
    },
    'zh': {
        'WebP Conversion Options': 'WebP 转换选项',
        'Conversion Options': '转换选项',
        'Lossless': '无损压缩',
        'Image Quality': '图像质量',
        'Exif Data': '保留EXIF数据',
        'ICC Profile': '保留ICC配置文件',
        'Transparent RGB': '保留透明背景(RGB)',
        'Exif Frame Options': 'EXIF 边框选项',
        'Caption Options': '边框文本选项',
        'Select Font': '选择字体',
        'Alignment': '文本对齐',
        'Center': '居中',
        'Left': '靠左',
        'Right': '靠右',
        'EXIF Easy Mode': '简易模式',
        'One line': '单行显示',
        'Text Color': '文本颜色',
        'BG Color': '背景颜色',
        'Loading...': '加载中...',
        'Automatically hide NONEDATA text': '自动隐藏空白数据',
        'EXIF Options': 'EXIF 选项',
        'Padding Option': '边距设定',
        'No Padding': '无边距',
        'Bottom': '底部边距',
        'Frame': '全身边距',
        'Save Exif Data': '保存EXIF信息',
        'Ratio': '比例',
        'Original': '原始比例',
        'Square': '1:1 (正方形)',
        '4:5': '4:5',
        'Quality': '质量',
        'Image Type': '图像格式',
        'JPEG': 'JPEG',
        'PNG': 'PNG',
        'WebP': 'WebP',
        'Settings': '设置',
        'Language': '语言',
        'English': 'English',
        'Korean': '韩文',
        'Japanese': '日文',
        'Add Text': '添加文本',
        'Watermark Options': '水印选项',
        'Watermark Text': '水印文本',
        'Paddie。': 'Paddie。',
        '+': '+',
        'Enable': '启用',
        'Options': '选项',
        'TBD': '开发中',
        'Show Preview': '预览',
        "Save to selected photo's path": '保存到原始照片路径',
        '-': '-',
        'Resize Options': '调整大小选项',
        'Files': '文件',
        'Add Files': '添加文件',
        'Ctrl+O': 'Ctrl+O',
        'Remove Files ...': '移除文件 ...',
        'Exit': '退出',
        'Clear List': '清空列表',
        'Preferences': '偏好设置...',
        'Information': '关于',
        'Version: ': '版本: ',
        'Contact: ': '联系方式: ',
        'License: ': '许可证: ',
        'Axis': '基准轴',
        'Width': '宽度',
        'Height': '高度',
        'Longest': '长边',
        'Shortest': '短边',
        'Size': '大小'
    }
}

for lang in ['ko', 'ja', 'zh']:
    tree = ET.parse(f'resources/translations_{lang}.ts')
    root = tree.getroot()
    dictionary = translations[lang]

    for message in root.iter('message'):
        source = message.find('source')
        if source is not None and source.text in dictionary:
            translation = message.find('translation')
            if translation is not None:
                translation.text = dictionary[source.text]
                if 'type' in translation.attrib:
                    del translation.attrib['type']
                
    tree.write(f'resources/translations_{lang}.ts', encoding='utf-8', xml_declaration=True)

print("TS files successfully updated with dictionary translations!")
